check:
  - thoth-build
build:
  build-stratergy: "Dockerfile"
  dockerfile-path: "build/Dockerfile.modh"
  custom-tag: "latest"
  registry: "quay.io"
  registry-org: "modh"
  registry-project: "odh-operator-image"
  registry-secret: "modh-pusher-secret"
